Algoritmo "Orientação a Objetos"

tipo

cadastroCliente = registro

 nome : caracter
 rg : caracter
 idade : inteiro
fimregistro

Var

cliente1 : cadastroCliente

Inicio

Escreval ("Digite seu nome: ")
leia(cliente1.nome)

Escreval ("Digite seu rg: ")
leia(cliente1.rg)

Escreval ("Digite seu idade: ")
leia(cliente1.idade)

Escreval("Nome: ", cliente1.Nome, " - RG: ", cliente1.rg, " Idade: ", cliente1.idade)


Fimalgoritmo